config/routes.rb
MyParking::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)

  resources :parkings
  
  root :to => 'parkings#index'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/parking.rb
class Parking < ActiveRecord::Base
  attr_accessible :address, :gmaps, :latitude, :longitude, :name

  acts_as_gmappable

  def gmaps4rails_address
    address
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
  # GET /parkings
  # GET /parkings.json
  def index
    @parkings = Parking.all
    @json = Parking.all.to_gmaps4rails

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @parkings }
    end
  end

  # GET /parkings/1
  # GET /parkings/1.json
  def show
    @parking = Parking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @parking }
    end
  end

  # GET /parkings/new
  # GET /parkings/new.json
  def new
    @parking = Parking.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @parking }
    end
  end

  # GET /parkings/1/edit
  def edit
    @parking = Parking.find(params[:id])
  end

  # POST /parkings
  # POST /parkings.json
  def create
    @parking = Parking.new(params[:parking])

    respond_to do |format|
      if @parking.save
        format.html { redirect_to @parking, notice: 'Parking was successfully created.' }
        format.json { render json: @parking, status: :created, location: @parking }
      else
        format.html { render action: "new" }
        format.json { render json: @parking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /parkings/1
  # PUT /parkings/1.json
  def update
    @parking = Parking.find(params[:id])

    respond_to do |format|
      if @parking.update_attributes(params[:parking])
        format.html { redirect_to @parking, notice: 'Parking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @parking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parkings/1
  # DELETE /parkings/1.json
  def destroy
    @parking = Parking.find(params[:id])
    @parking.destroy

    respond_to do |format|
      format.html { redirect_to parkings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/views/layouts/_navigation.html.erb
<navigation>  
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign In", new_user_session_path %> 
   <% end %>
</navigation>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyParking</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'gmaps4rails' %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> 

<%= render "layouts/navigation" %>

<%= yield %>

<%= yield :scripts %>

</body>
</html>

app/views/parkings/_form.html.erb
<%= form_for(@parking) do |f| %>
  <% if @parking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parking.errors.count, "error") %> prohibited this parking from being saved:</h2>

      <ul>
      <% @parking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :gmaps %><br />
    <%= f.check_box :gmaps %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parkings/edit.html.erb
<h1>Editing parking</h1>

<%= render 'form' %>

<%= link_to 'Show', @parking %> |
<%= link_to 'Back', parkings_path %>

app/views/parkings/index.html.erb
<h1>Listing parkings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th>Gmaps</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parkings.each do |parking| %>
  <tr>
    <td><%= parking.name %></td>
    <td><%= parking.address %></td>
    <td><%= parking.longitude %></td>
    <td><%= parking.latitude %></td>
    <td><%= parking.gmaps %></td>
    <td><%= link_to 'Show', parking %></td>
    <td><%= link_to 'Edit', edit_parking_path(parking) %></td>
    <td><%= link_to 'Destroy', parking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Parking', new_parking_path %>
<%= gmaps4rails(@json) %>

app/views/parkings/new.html.erb
<h1>New parking</h1>

<%= render 'form' %>

<%= link_to 'Back', parkings_path %>

app/views/parkings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @parking.name %>
</p>

<p>
  <b>Address:</b>
  <%= @parking.address %>
</p>

<p>
  <b>Longitude:</b>
  <%= @parking.longitude %>
</p>

<p>
  <b>Latitude:</b>
  <%= @parking.latitude %>
</p>

<p>
  <b>Gmaps:</b>
  <%= @parking.gmaps %>
</p>


<%= link_to 'Edit', edit_parking_path(@parking) %> |
<%= link_to 'Back', parkings_path %>